### ISSUE TITLE
[BUG] Cluster registration URL is not shown 

### ISSUE THREAD

**Issue by m-ildefons** [harvester/harvester-ui-extension#38]
Reproduce:

Install Rancher v2.10.0-rc3
Install Harvester UI plugin
Visit "Virtualization Management" page
Click "Import Existing" button to import existing Harvester cluster

No registration URL visible. Importing Harvester cluster impossible

![Screenshot at 2024-11-15 12-30-19](https://github.com/user-attachments/assets/da412330-1dc9-4a1e-a248-d092e48c4b49)

**Comment by a110605** [comment]
I can reproduce this issue using harvester-ui-extension v1.0.1. cc @torchiaf 

Using v1.0.0 is fine.

The error reported after creating cluster registration endpoint.

```
Error in fetch(): Error: Unknown schema for type: clusterregistrationtoken
```
<img width="1495" alt="Screenshot 2024-11-18 at 1 54 12 PM" src="https://github.com/user-attachments/assets/14338db7-c12e-4d56-981f-e8a67e617335">

**Comment by a110605** [comment]
Testing with [rancher-v2.10-rc4](https://hub.docker.com/r/rancher/rancher/tags?name=2.10) image with harvester-ui-extension v1.0.0 (branch : gh-pages),  the registration URL is succesfully show up.

<img width="1496" alt="image" src="https://github.com/user-attachments/assets/d1405b64-62c3-436d-9c1f-68e32d4708b5">


@m-ildefons could you try again using harvester-ui-extension gh-pages branch ?

**Comment by m-ildefons** [comment]
Hi Andy,
with v2.10.0-rc4 it works indeed as expected.
I'll close this issue then, since there is nothing to be done.
